package kotliquery

/**
 * Transactional Database session.
 */
class TransactionalSession(
    override val connection: Connection,
    override val returnGeneratedKeys: Boolean = true,
    override val autoGeneratedKeys: List<String> = listOf()
) : Session(connection, returnGeneratedKeys, autoGeneratedKeys) {}